#!/usr/bin/env python3
# vim: set ft=python:

import os
import sys
import json


try :
    data = json.loads(sys.stdin.read())
except (IOError):
    sys.exit()

if 'headers' not in data or 'HTTP_X_FORWARDED_EMAIL' not in data.get('headers'):
    sys.exit()

email = data.get('headers').get('HTTP_X_FORWARDED_EMAIL')
result = dict(
    email=email,
    password='',
    fullname=email.split('@')[0],
)

print(json.dumps(result))
